### ISSUE TITLE
Installation on Ubuntu 18.04 missing .yaml

### ISSUE THREAD

**Issue by dagewa** [stefsmeets/edtools#6]
Hi!
I installed edtools on Ubuntu 18.04 by `sudo python3 setup.py install`, but it appears not to put the .yaml files in the right place:
```
$ edtools.make_shelx
Traceback (most recent call last):
  File "/usr/local/bin/edtools.make_shelx", line 11, in <module>
    load_entry_point('edtools==0.1.0', 'console_scripts', 'edtools.make_shelx')()
  File "/home/fcx32934/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/fcx32934/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/home/fcx32934/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/home/fcx32934/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/edtools-0.1.0-py3.6.egg/edtools/make_shelx.py", line 7, in <module>
    TABLE = yaml.load(open(fin, "r"), Loader=yaml.Loader)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/edtools-0.1.0-py3.6.egg/edtools/atomlib.yaml'
```
Am I doing something wrong?

**Comment by stefsmeets** [comment]
I see I forgot to add those as package data. I will have a look next week, but I'm guessing that's it. I normally install my code as `python setup.py develop`, so it runs the code inplace. You could try that as a work-around.

**Comment by dagewa** [comment]
Thanks! `python setup.py develop` suits me just fine.
